// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvhXeDw7_r23pB-W9d6o77Dv8Tk-xQQo',
    appId: '1:485628385430:web:ca861b7f376d1cf12ecab7',
    messagingSenderId: '485628385430',
    projectId: 'snackbert-christried',
    authDomain: 'snackbert-christried.firebaseapp.com',
    storageBucket: 'snackbert-christried.firebasestorage.app',
    measurementId: 'G-44J5NP7J9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkEdBVpb4PMIKXBqNLN9VtHzphK1GGUwY',
    appId: '1:485628385430:android:059dd4e99e8499cc2ecab7',
    messagingSenderId: '485628385430',
    projectId: 'snackbert-christried',
    storageBucket: 'snackbert-christried.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhvhXeDw7_r23pB-W9d6o77Dv8Tk-xQQo',
    appId: '1:485628385430:web:ec840c1d9e169f7b2ecab7',
    messagingSenderId: '485628385430',
    projectId: 'snackbert-christried',
    authDomain: 'snackbert-christried.firebaseapp.com',
    storageBucket: 'snackbert-christried.firebasestorage.app',
    measurementId: 'G-0EYDCWQLGX',
  );
}
